tools: focus: automatically find keyboard port
In tool/focus, use find to get the /dev/ACM* port the keyboard is
connected to.

diff --git a/tools/focus b/tools/focus
--- a/tools/focus
+++ b/tools/focus
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# focus-test - Trivial Focus testing tool
-# Copyright (C) 2018  Keyboard.io, Inc.
+# focus-send - Trivial Focus testing tool
+# Copyright (C) 2018-2022  Keyboard.io, Inc.
 #
 # This program is free software: you can redistribute it and/or modify it under
 # the terms of the GNU General Public License as published by the Free Software
@@ -15,17 +15,53 @@
 
 set -e
 
-DEVICE="${DEVICE:-/dev/ttyACM0}"
+OS=$(uname -s)
 
-stty -F "${DEVICE}" 9600 raw -echo
+# igncr absorbs CR from Focus CRLF line endings
+# -echo is needed because raw doesn't turn it off on Linux
+STTY_ARGS="9600 raw igncr -echo"
 
-exec 3<"${DEVICE}"
+case ${OS} in
+    Linux)
+        # Use find to find the /dev/ACM* port the keyboard is connected to
+        # The first ACM* port is selected if multiple keyboard are connected
+        port="$(find /dev/ttyACM* | head -1)"
+      
+        DEVICE="${DEVICE:-$port}"
+        ;;
+    Darwin)
+        # bash on macOS has a bug that randomly drops serial input
+        if [ -n "$BASH_VERSION" ] && [ -x /bin/dash ]; then
+            # Prevent loop in case someone exported it
+            export -n BASH_VERSION
+            exec /bin/dash "$0" "$@"
+        fi
+        DEVICE="${DEVICE:-/dev/cu.usbmodemCkbio01E}"
+        ;;
+    *)
+        echo "Error Unknown OS : ${OS}" >&2
+        exit 1
+        ;;
+esac
+
+# Redirect prior to running stty, because macOS sometimes resets termios
+# state upon last close of a terminal device.
+exec < "${DEVICE}"
+# shellcheck disable=SC2086 # intentional word splitting
+stty $STTY_ARGS
+
+read_reply () {
+    while read -r line; do
+        if [ "${line}" = "." ]; then
+            break
+        fi
+        echo "${line}"
+    done
+}
+
+# Flush any invalid commands out of input buffer.
+# This could happen after a failed upload.
+echo ' ' > "${DEVICE}"
+read_reply > /dev/null
 echo "$@" >"${DEVICE}"
-
-while read -r line <&3; do
-    line="$(echo -n "${line}" | tr -d '\r')"
-    if [ "${line}" == "." ]; then
-        break
-    fi
-    echo "${line}"
-done
+read_reply
